<?php
require_once 'config/analytics.php';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Slingo Board Checker</title>
    <link rel="stylesheet" href="css/slingo.css">
    <?php renderGoogleAnalytics(); ?>
</head>
<body>
    <div class="container">
        <header>
            <h1>Slingo Board Checker</h1>
            <p>Configure your board and get optimal wild card placement recommendations</p>
        </header>

        <div id="slingo-container">
            <!-- Slingo Board -->
            <div class="board-section">
                <h2>Slingo Board</h2>
                <div class="board-instructions">
                    <p><strong>Instructions:</strong> Click on the tiles below to mark them as covered. The numbers shown are just for reference - wild placement is based on position, not numbers.</p>
                    <div class="board-legend">
                        <div class="legend-item">
                            <div class="legend-marker covered"></div>
                            <span>Covered Cell</span>
                        </div>
                        <div class="legend-item">
                            <div class="legend-marker wild-marker"></div>
                            <span>Wild Card</span>
                        </div>
                        <div class="legend-item">
                            <div class="legend-marker super-wild-marker"></div>
                            <span>Super Wild</span>
                        </div>
                    </div>
                </div>
                <div id="slingo-board" class="slingo-grid">
                    <!-- 5x5 grid will be generated by JavaScript -->
                </div>
                <button id="reset-board" class="btn btn-secondary">Reset Board</button>
            </div>

            <!-- Draw Configuration -->
            <div class="config-section">
                <h2>Draw Configuration</h2>
                <div id="draw-rows">
                    <!-- Dynamic draw rows will be generated by JavaScript -->
                </div>
                <div class="row-controls">
                    <button id="add-row" class="btn btn-primary">Add Draw Row</button>
                    <button id="remove-row" class="btn btn-secondary" disabled>Remove Row</button>
                </div>
            </div>

            <!-- Controls -->
            <div class="controls-section">
                <button id="submit-analysis" class="btn btn-success">Get Optimal Strategy</button>
            </div>

            <!-- Results -->
            <div id="results" class="results-section" style="display: none;">
                <h2>Analysis Results</h2>
                <div id="results-content"></div>
            </div>
        </div>
    </div>

    <script src="js/slingo.js"></script>
</body>
</html>
