<?php
require_once 'config/analytics.php';
require_once 'config/seo.php';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <?php renderSEOMetaTags(); ?>
    <link rel="stylesheet" href="css/slingo.css">
    <?php renderAdditionalSEO(); ?>
    <?php renderStructuredData(); ?>
    <?php renderGoogleAnalytics(); ?>
</head>
<body>
    <div class="container">
        <header role="banner">
            <h1>Slingo Board Checker</h1>
            <p>Configure your board and get optimal wild card placement recommendations</p>
            <nav aria-label="Main navigation">
                <ul>
                    <li><a href="#slingo-board-section" aria-label="Go to Slingo board section">Board</a></li>
                    <li><a href="#draw-configuration" aria-label="Go to draw configuration section">Configuration</a></li>
                    <li><a href="#results" aria-label="Go to results section">Results</a></li>
                    <li><a href="https://ko-fi.com/stringsnkeys" target="_blank" rel="noopener noreferrer" class="ko-fi-nav-link" aria-label="Support this project on Ko-fi">☕ Support</a></li>
                </ul>
            </nav>
        </header>

        <main role="main">
            <div id="slingo-container">
                <!-- Slingo Board Section -->
                <section id="slingo-board-section" class="board-section" aria-labelledby="board-heading">
                    <h2 id="board-heading">Slingo Board</h2>
                    <div class="board-instructions">
                        <p><strong>Instructions:</strong> Click on the tiles below to mark them as covered. The numbers shown are just for reference - wild placement is based on position, not numbers.</p>
                        <div class="board-legend" role="img" aria-label="Legend showing covered cell, wild card, and super wild card markers">
                            <div class="legend-item">
                                <div class="legend-marker covered" aria-hidden="true"></div>
                                <span>Covered Cell</span>
                            </div>
                            <div class="legend-item">
                                <div class="legend-marker wild-marker" aria-hidden="true"></div>
                                <span>Wild Card</span>
                            </div>
                            <div class="legend-item">
                                <div class="legend-marker super-wild-marker" aria-hidden="true"></div>
                                <span>Super Wild</span>
                            </div>
                        </div>
                    </div>
                    <div id="slingo-board" class="slingo-grid" role="grid" aria-label="5x5 Slingo board" tabindex="0">
                        <!-- 5x5 grid will be generated by JavaScript -->
                    </div>
                    <button id="reset-board" class="btn btn-secondary" aria-label="Reset the Slingo board to clear all covered positions">Reset Board</button>
                </section>

            <!-- Draw Configuration -->
            <div class="config-section">
                <h2>Draw Configuration</h2>
                <div id="draw-rows">
                    <!-- Dynamic draw rows will be generated by JavaScript -->
                </div>
                <div class="row-controls">
                    <button id="add-row" class="btn btn-primary">Add Draw Row</button>
                    <button id="remove-row" class="btn btn-secondary" disabled>Remove Row</button>
                </div>
            </div>

            <!-- Controls -->
            <div class="controls-section">
                <button id="submit-analysis" class="btn btn-success">Get Optimal Strategy</button>
            </div>

            <!-- Results -->
            <div id="results" class="results-section" style="display: none;">
                <h2>Analysis Results</h2>
                <div id="results-content"></div>
            </div>
        </div>
    </div>

    <!-- Footer with Support -->
    <footer role="contentinfo" class="footer">
        <div class="footer-content">
            <div class="support-section">
                <h3>Support This Project</h3>
                <p>If you find this tool helpful, consider supporting its development:</p>
                <a href="https://ko-fi.com/stringsnkeys" 
                   target="_blank" 
                   rel="noopener noreferrer" 
                   class="ko-fi-button"
                   aria-label="Support this project on Ko-fi">
                    <span class="ko-fi-icon">☕</span>
                    Buy me a coffee on Ko-fi
                </a>
            </div>
            <div class="footer-info">
                <p>&copy; 2025 Slingo Board Checker. Made with ❤️ for Slingo players.</p>
                <p><a href="https://ko-fi.com/stringsnkeys" target="_blank" rel="noopener noreferrer">Support on Ko-fi</a></p>
            </div>
        </div>
    </footer>

    <script src="js/slingo.js"></script>
</body>
</html>
