name: CI

on:
  push:
    branches: [ main, develop, simplify-heuristic ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Suite
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, json
        ini-values: error_reporting=E_ALL
        coverage: none
        
    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-
        
    - name: Install dependencies
      run: |
        if [ -f composer.json ]; then
          composer install --no-progress --prefer-dist --optimize-autoloader
        else
          echo "No composer.json found, skipping dependency installation"
        fi
      
    - name: Lint PHP files
      run: |
        if [ -f composer.json ]; then
          composer run syntax-check
        else
          find . -name "*.php" -not -path "./vendor/*" -exec php -l {} \;
        fi
      
    - name: Run tests
      run: |
        if [ -f composer.json ]; then
          composer run test
        else
          php tests/simple_test_runner.php
        fi
      
    - name: Test application startup
      run: |
        timeout 10s php -S localhost:8000 -t . > /dev/null 2>&1 &
        sleep 2
        curl -f http://localhost:8000/index.php > /dev/null
        
  compatibility:
    runs-on: ubuntu-latest
    name: PHP Compatibility
    strategy:
      matrix:
        php: ['7.4', '8.0', '8.3']
        
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup PHP ${{ matrix.php }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, json
        
    - name: Install dependencies
      run: |
        if [ -f composer.json ]; then
          composer install --no-progress --prefer-dist --optimize-autoloader
        else
          echo "No composer.json found, skipping dependency installation"
        fi
      
    - name: Test with PHP ${{ matrix.php }}
      run: |
        if [ -f composer.json ]; then
          composer run test
        else
          php tests/simple_test_runner.php
        fi
