name: Quick Tests

on:
  push:
    branches: [ main, develop, simplify-heuristic ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quick-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP 8.1
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, json
        
    - name: Install Composer dependencies
      run: |
        if [ -f composer.json ]; then
          composer install --prefer-dist --no-progress --no-interaction
        else
          echo "No composer.json found, skipping dependency installation"
        fi
        
    - name: Run PHP syntax check
      run: find . -name "*.php" -not -path "./vendor/*" | xargs -I {} php -l {}
      
    - name: Run automated tests
      run: php tests/simple_test_runner.php
      
    - name: Validate manual tests can run
      run: php tests/manual/run_manual_tests.php
      
    - name: Test main application
      run: |
        php -S localhost:8000 -t . &
        sleep 3
        curl -f http://localhost:8000/index.php
        echo "Application is working"
